-- ============================================================
-- Household Finance Ledger — initial schema
-- Money is stored as integer cents (bigint). Never floats.
-- Every household-scoped table has RLS on household_id.
-- ============================================================

-- ---------- Lookup / reference tables (global, read-only) ----------

create table transaction_type (
  id smallint generated by default as identity primary key,
  name text not null unique
);

create table transaction_category (
  id smallint generated by default as identity primary key,
  transaction_type_id smallint not null references transaction_type (id),
  name text not null,
  unique (transaction_type_id, name)
);

create table transaction_frequency (
  id smallint generated by default as identity primary key,
  name text not null unique
);

create table account_type (
  id smallint generated by default as identity primary key,
  name text not null unique
);

-- ---------- Core tables ----------

create table household (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table profile (
  id uuid primary key references auth.users (id) on delete cascade,
  household_id uuid not null references household (id),
  display_name text not null,
  created_at timestamptz not null default now()
);

create table account (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references household (id),
  name text not null,
  institution text not null,
  account_type_id smallint not null references account_type (id),
  is_hub boolean not null default false,
  created_at timestamptz not null default now()
);

create table recurring_template (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references household (id),
  account_id uuid not null references account (id),
  transaction_type_id smallint not null references transaction_type (id),
  transaction_category_id smallint not null references transaction_category (id),
  transaction_frequency_id smallint not null references transaction_frequency (id),
  source_name text not null,
  amount_cents bigint not null,
  due_day smallint not null check (due_day between 1 and 31),
  start_date date not null,
  end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table transaction (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references household (id),
  account_id uuid not null references account (id),
  transaction_type_id smallint not null references transaction_type (id),
  transaction_category_id smallint not null references transaction_category (id),
  transaction_frequency_id smallint references transaction_frequency (id),
  recurring_template_id uuid references recurring_template (id) on delete set null,
  source_name text not null,
  txn_date date not null,
  due_date date,
  amount_cents bigint not null,
  note text,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index transaction_household_date_idx on transaction (household_id, txn_date desc);
create index transaction_account_idx on transaction (account_id);

create table transfer (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references household (id),
  from_account_id uuid not null references account (id),
  to_account_id uuid not null references account (id),
  amount_cents bigint not null,
  txn_date date not null,
  note text,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now(),
  check (from_account_id <> to_account_id)
);

-- ---------- Import staging ----------

create table statement_import (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references household (id),
  account_id uuid not null references account (id),
  file_path text not null,
  bank_format text not null,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'committed')),
  uploaded_by uuid references auth.users (id),
  created_at timestamptz not null default now()
);

create table import_row (
  id uuid primary key default gen_random_uuid(),
  statement_import_id uuid not null references statement_import (id) on delete cascade,
  raw_data jsonb not null,
  parsed_source_name text,
  parsed_date date,
  parsed_amount_cents bigint,
  suggested_category_id smallint references transaction_category (id),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'edited')),
  committed_transaction_id uuid references transaction (id)
);

-- ---------- updated_at trigger ----------

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

create trigger recurring_template_updated_at before update on recurring_template
  for each row execute function set_updated_at();
create trigger transaction_updated_at before update on transaction
  for each row execute function set_updated_at();

-- ---------- Auth: auto-provision profile into the household ----------
-- Two-person single-household setup: the first user to sign up creates the
-- household; later signups join it. (Multi-household onboarding can replace
-- this trigger later without schema changes.)

create or replace function handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  hid uuid;
begin
  select id into hid from household order by created_at limit 1;
  if hid is null then
    insert into household (name) values ('Our Household') returning id into hid;
  end if;
  insert into profile (id, household_id, display_name)
  values (new.id, hid, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)));
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------- RLS ----------

-- Helper: the caller's household id (from their profile row).
create or replace function current_household_id()
returns uuid
language sql
stable
security definer set search_path = public
as $$
  select household_id from profile where id = auth.uid()
$$;

-- Lookups: readable by any signed-in user, never writable from the client.
alter table transaction_type enable row level security;
alter table transaction_category enable row level security;
alter table transaction_frequency enable row level security;
alter table account_type enable row level security;

create policy "lookup read" on transaction_type for select to authenticated using (true);
create policy "lookup read" on transaction_category for select to authenticated using (true);
create policy "lookup read" on transaction_frequency for select to authenticated using (true);
create policy "lookup read" on account_type for select to authenticated using (true);

-- Household + profile
alter table household enable row level security;
create policy "own household" on household for select to authenticated
  using (id = current_household_id());

alter table profile enable row level security;
create policy "household profiles" on profile for select to authenticated
  using (household_id = current_household_id());
create policy "update own profile" on profile for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid() and household_id = current_household_id());

-- Household-scoped tables: full CRUD within the caller's household.
alter table account enable row level security;
create policy "household rows" on account for all to authenticated
  using (household_id = current_household_id())
  with check (household_id = current_household_id());

alter table recurring_template enable row level security;
create policy "household rows" on recurring_template for all to authenticated
  using (household_id = current_household_id())
  with check (household_id = current_household_id());

alter table transaction enable row level security;
create policy "household rows" on transaction for all to authenticated
  using (household_id = current_household_id())
  with check (household_id = current_household_id());

alter table transfer enable row level security;
create policy "household rows" on transfer for all to authenticated
  using (household_id = current_household_id())
  with check (household_id = current_household_id());

alter table statement_import enable row level security;
create policy "household rows" on statement_import for all to authenticated
  using (household_id = current_household_id())
  with check (household_id = current_household_id());

alter table import_row enable row level security;
create policy "household rows" on import_row for all to authenticated
  using (exists (select 1 from statement_import si
                 where si.id = statement_import_id
                   and si.household_id = current_household_id()))
  with check (exists (select 1 from statement_import si
                      where si.id = statement_import_id
                        and si.household_id = current_household_id()));

-- ---------- Storage bucket for uploaded statements ----------

insert into storage.buckets (id, name, public) values ('statements', 'statements', false);

create policy "household statement files" on storage.objects for all to authenticated
  using (bucket_id = 'statements' and (storage.foldername(name))[1] = current_household_id()::text)
  with check (bucket_id = 'statements' and (storage.foldername(name))[1] = current_household_id()::text);

-- ---------- Seed lookup data ----------

insert into transaction_type (name) values ('debt'), ('recurring'), ('spending');

insert into transaction_category (transaction_type_id, name)
select tt.id, c.name
from transaction_type tt
join lateral (
  values
    ('debt', 'credit card'), ('debt', 'loan'),
    ('recurring', 'debts'), ('recurring', 'utils'), ('recurring', 'subs'),
    ('spending', 'groceries'), ('spending', 'shopping'), ('spending', 'dining'),
    ('spending', 'maintenance'), ('spending', 'fun')
) as c (type_name, name) on c.type_name = tt.name;

insert into transaction_frequency (name) values ('weekly'), ('monthly'), ('yearly');

insert into account_type (name) values ('billing'), ('spending'), ('saving'), ('deposit');
